export {default as Login} from "./Login"
export {default as SingIn} from "./SingIn"
export {default as Profile} from "./Profile"
export {default as Race} from "./Race"
export {default as Playing} from "./Playing"